###Get employees
GET http://localhost:3000/Mobile&Laptop

###Post user
POST http://localhost:3000/user
Content-Type: application/json

{
       "name":"prashant",
       "email":"adarshjondhale@example.in",
       "profile": "",
       "status": "Active",
       "role":"Admin"
}

###Get cats
GET http://localhost:3000/Homepage


###Post user
POST http://localhost:3000/Homepage
Content-Type: application/json

{
       
    "name": "Singularity Men's ",
    "profile": "https://cdn.shopclues.com/images1/thumbnails/114621/320/320/152497670-114621560-1625832145.jpg",
    "price1": "349",
    "price": 349,
    "description": "Singularity Men's White Casual Regular Fit Short Kurta"
}

### GET all homepage
GET http://localhost:3000/Homepage?_limit=10&_page=1